"use client";

import { type ButtonHTMLAttributes, type CSSProperties, forwardRef } from "react";
import { BitmapText } from "./bitmap-font";
import { assetUrl } from "./asset-url";
import outlinePng from "./assets/button-outline.png";
import outlinePressedPng from "./assets/button-outline-pressed.png";
import fillPng from "./assets/button-fill.png";
import fillPressedPng from "./assets/button-fill-pressed.png";
import "./nine-slice-button.css";

/**
 * D8 standard button — a 9-slice pixel-art button from the kit's bundled
 * button sprites:
 *
 *   • Fill     (16×16) — the full rounded-rect silhouette (white), used as a
 *                        single 9-slice mask. The element behind it paints a
 *                        two-stop gradient (face `color` → `shadowColor` bevel
 *                        for the bottom BEVEL_H px), so one painted box yields
 *                        both tones with NO seam between them.
 *   • Outlines (16×16) — black frame + inner white highlight, drawn on top.
 *
 * (The fill silhouette is generated by unioning the original Light/Dark Fill
 * art; doing it as one masked gradient avoids the hairline gap two abutting
 * masked bands leak on fractional scaling.) The outline is a `border-image`.
 *
 * Pixel size is decoupled from button size. `pixelScale` is the rendered size
 * of ONE source pixel (any CSS length) — set it to a sibling sprite's native
 * scale (e.g. the cabinet renders at `0.4vh`/px) so the button's pixels match
 * instead of ballooning when the button is large. All crisp detail (rounded
 * corners, outline thickness, bevel lip) is `pixelScale * n`; only the solid
 * face stretches to fill any extra height/width via 9-slice. The outline's
 * inner highlight is held in a fixed `BEVEL_H`-px bottom slice, so it stays a
 * single crisp row pinned to the face/bevel seam at any size. (`scale` is a px
 * shorthand: pixelScale = `${scale}px`.)
 */

const SRC = {
  outline:        assetUrl(outlinePng),
  fill:           assetUrl(fillPng),
  // Pressed twins (both 16×16). The whole cap is shifted DOWN 2 px — the top
  // 2 rows are cleared, the bevel band is thinned 3 px → 1 px, and the bottom
  // frame stays put — so the button reads as sunk into its socket: a 2-px gap
  // opens above and the bottom edge holds. Because the art moved down, the
  // 9-slice top inset grows to TOP_PRESSED (2-px gap + 3-px corner) and the
  // outline's bottom inset shrinks to BEVEL_H_PRESSED. Swapped in on :active
  // via the `--outline` / `--fill-mask` vars.
  outlinePressed: assetUrl(outlinePressedPng),
  fillPressed:    assetUrl(fillPressedPng),
};

// Native-px geometry of the source art. The press state shifts the cap down by
// (TOP_PRESSED − CORNER) = 2 px and thins the lip by (BEVEL_H − BEVEL_H_PRESSED)
// = 2 px; both are flipped through CSS vars in the :active rule.
const UNIT_H          = 16; // full button height
const CORNER          =  3; // resting 9-slice inset — rounded-corner staircase depth
const TOP_PRESSED     =  5; // pressed top inset: 2-px sink gap + 3-px corner
const BEVEL_H         =  6; // resting dark-fill band height (outline bottom inset)
const BEVEL_H_PRESSED =  4; // pressed dark-fill band height — seam sits 2 px lower

const DEFAULT_SCALE = 4;
const DEFAULT_LIGHT = "#ffd21e"; // bright, saturated gold
// shadowColor defaults to a darkened `color`.

/** Multiply a #rgb / #rrggbb hex toward black by fraction `f` (0–1). */
function darken(hex: string, f: number): string {
  const m = hex.replace("#", "");
  const n = m.length === 3 ? m.split("").map((c) => c + c).join("") : m;
  const ch = (i: number) => Math.round(parseInt(n.slice(i, i + 2), 16) * (1 - f));
  return `#${[ch(0), ch(2), ch(4)].map((v) => v.toString(16).padStart(2, "0")).join("")}`;
}

/**
 * Build a 9-slice mask-border style (standard + -webkit-) from a white fill PNG.
 * `source` is a full CSS image value (a `url(...)` or a `var(...)` resolving to
 * one); `slice` / `width` are full 4-side shorthands ("top right bottom left",
 * `slice` ending in `fill` so the center silhouette shows through). They take
 * vars so the rest/pressed swap happens in CSS. Cast through a string record
 * because the vendor longhands aren't in React's CSSProperties.
 */
function maskBorder(source: string, slice: string, width: string): CSSProperties {
  const v: Record<string, string> = {
    WebkitMaskBoxImageSource: source,
    WebkitMaskBoxImageSlice:  slice,
    WebkitMaskBoxImageWidth:  width,
    WebkitMaskBoxImageRepeat: "stretch",
    maskBorderSource: source,
    maskBorderSlice:  slice,
    maskBorderWidth:  width,
    maskBorderRepeat: "stretch",
  };
  return v as CSSProperties;
}

export interface NineSliceButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  /** Bright, saturated face color (tints the Light Fill). */
  color?: string;
  /** Darker bevel / shadow color (tints the Dark Fill). Defaults to a darkened `color`. */
  shadowColor?: string;
  /** Label color. Defaults to a near-black for contrast on the bright face. */
  textColor?: string;
  /** Rendered size of one source pixel, as any CSS length (e.g. "0.4vh", "4px"). Overrides `scale`. */
  pixelScale?: string;
  /** Px shorthand for pixelScale (pixelScale = `${scale}px`). */
  scale?: number;
  /** Total button height. Defaults to the native 12-px height; larger values stretch the face. */
  height?: string;
  /** Rendered size of one label font-pixel (CSS length). Defaults to half a structural pixel. */
  labelPixel?: string;
}

export const NineSliceButton = forwardRef<HTMLButtonElement, NineSliceButtonProps>(function NineSliceButton(
  { color = DEFAULT_LIGHT, shadowColor, textColor = "#1a1410", pixelScale, scale = DEFAULT_SCALE, height, labelPixel, className, style, children, ...rest },
  ref,
) {
  const ps = pixelScale ?? `${scale}px`;
  // native-px count → rendered length at the current pixel scale.
  const u = (n: number) => `calc(${ps} * ${n})`;
  const h = height ?? u(UNIT_H);
  const bevel = shadowColor ?? darken(color, 0.32);
  // The label rides the retro 8×8 bitmap font (basicpixel) so it reads as
  // pixel-art arcade type rather than a smooth UI font. Sized in font-pixels
  // that scale with the button's unit; uppercased, with "…" → "..." since the
  // atlas has no ellipsis glyph.
  const labelPx = labelPixel ?? `calc(${ps} * 0.5)`;
  const label =
    typeof children === "string" || typeof children === "number" ? (
      <BitmapText unit={labelPx} tracking={`calc(${labelPx} * -0.5)`}>
        {String(children).replace(/…/g, "...").toUpperCase()}
      </BitmapText>
    ) : (
      children
    );

  const layerBase: CSSProperties = {
    position:       "absolute",
    left:           0,
    right:          0,
    imageRendering: "pixelated",
    pointerEvents:  "none",
  };

  // Press-sensitive values are routed through CSS vars so a single `:active`
  // rule (in the stylesheet) flips them for mouse, touch AND keyboard — no
  // React state, no re-render. The four live vars — `--slice-top` (top 9-slice
  // inset), `--bevel-h` (bottom inset + gradient seam), `--outline`, `--fill-
  // mask` — are SET only in the stylesheet (default vs :active) so :active wins
  // over these inline styles. Here we expose the unit plus the rest/press
  // OPERANDS the stylesheet selects between, keeping every magic number/URL in
  // one place. `topLen`/`bevelLen` resolve the live insets to a rendered length.
  const topLen   = `calc(${ps} * var(--slice-top))`;
  const bevelLen = `calc(${ps} * var(--bevel-h))`;
  const cssVars = {
    "--u":               ps,
    "--slice-top-rest":  String(CORNER),
    "--slice-top-press": String(TOP_PRESSED),
    "--bevel-rest":      String(BEVEL_H),
    "--bevel-press":     String(BEVEL_H_PRESSED),
    "--outline-rest":    `url("${SRC.outline}")`,
    "--outline-press":   `url("${SRC.outlinePressed}")`,
    "--fill-rest":       `url("${SRC.fill}")`,
    "--fill-press":      `url("${SRC.fillPressed}")`,
  } as Record<string, string>;

  return (
    <button
      ref={ref}
      className={`nine-btn font-mono${className ? ` ${className}` : ""}`}
      style={{
        ...(cssVars as CSSProperties),
        position:       "relative",
        display:        "inline-flex",
        alignItems:     "center",
        justifyContent: "center",
        height:         h,
        minWidth:       u(16),
        // Content rides the light face, so reserve the fixed bevel lip as
        // bottom padding and give a little breathing room each side.
        padding:        `0 ${u(4)} ${u(BEVEL_H)}`,
        border:         "none",
        background:     "none",
        color:          textColor,
        fontSize:       u(3.5),
        fontWeight:     700,
        letterSpacing:  "0.12em",
        textTransform:  "uppercase",
        lineHeight:     1,
        whiteSpace:     "nowrap",
        cursor:         "pointer",
        ...style,
      }}
      {...rest}
    >
      {/* Tinted fill — ONE silhouette-masked box with a two-stop gradient: the
          face color down to the bevel line, then the bevel color for the fixed
          lip. A single painted element means there's no sub-pixel seam between
          face and bevel (two abutting masked bands used to leak a hairline of
          the dark background on fractional scaling). */}
      <span
        aria-hidden
        style={{
          ...layerBase,
          top:        0,
          bottom:     0,
          zIndex:     0,
          background: `linear-gradient(to bottom, ${color} 0, ${color} calc(100% - ${bevelLen}), ${bevel} calc(100% - ${bevelLen}), ${bevel} 100%)`,
          // Silhouette mask. Top inset is the live `--slice-top` (grows on press
          // to hold the 2-px sink gap + corner); bottom/sides stay CORNER. The
          // gradient seam (at 100% − bevelLen) and the mask's pressed top-gap
          // together drop the cap and thin the lip.
          ...maskBorder(
            "var(--fill-mask)",
            `var(--slice-top) ${CORNER} ${CORNER} ${CORNER} fill`,
            `${topLen} ${u(CORNER)} ${u(CORNER)} ${u(CORNER)}`,
          ),
        }}
      />
      {/* Black outline + white highlight — drawn over both fills. Top corners
          and the whole bevel band (incl. the highlight row) keep a fixed pixel
          size; only the plain side-rails stretch. */}
      <span
        aria-hidden
        style={{
          ...layerBase,
          top:               0,
          bottom:            0,
          zIndex:            2,
          borderStyle:       "solid",
          borderWidth:       `${topLen} ${u(CORNER)} ${bevelLen} ${u(CORNER)}`,
          borderColor:       "transparent",
          borderImageSource: `var(--outline)`,
          borderImageSlice:  `var(--slice-top) ${CORNER} var(--bevel-h) ${CORNER} fill`,
          borderImageWidth:  `${topLen} ${u(CORNER)} ${bevelLen} ${u(CORNER)}`,
          borderImageRepeat: "stretch",
        }}
      />
      <span
        className="nine-btn__content"
        // Nudged down one button-pixel: the pixel caps otherwise sit optically
        // high on the face. `top` (not transform) so the :active press, which
        // animates transform on this span, stays independent.
        style={{ position: "relative", top: u(1), zIndex: 3, display: "inline-flex", alignItems: "center", gap: u(1.5) }}
      >
        {label}
      </span>
    </button>
  );
});
