"use client";

import { type ButtonHTMLAttributes, type CSSProperties, forwardRef } from "react";
import { BitmapText } from "./bitmap-font";
import { assetUrl } from "./asset-url";
import outlinePng from "./assets/button-outline.png";
import fillPng from "./assets/button-fill.png";
import "./nine-slice-button.css";

/**
 * D8 standard button — a 9-slice pixel-art button from the kit's bundled
 * button sprites:
 *
 *   • Fill     (16×16) — the full rounded-rect silhouette (white), used as a
 *                        single 9-slice mask. The element behind it paints a
 *                        two-stop gradient (face `color` → `shadowColor` bevel
 *                        for the bottom BEVEL_H px), so one painted box yields
 *                        both tones with NO seam between them.
 *   • Outlines (16×16) — black frame + inner white highlight, drawn on top.
 *
 * (The fill silhouette is generated by unioning the original Light/Dark Fill
 * art; doing it as one masked gradient avoids the hairline gap two abutting
 * masked bands leak on fractional scaling.) The outline is a `border-image`.
 *
 * Pixel size is decoupled from button size. `pixelScale` is the rendered size
 * of ONE source pixel (any CSS length) — set it to a sibling sprite's native
 * scale (e.g. the cabinet renders at `0.4vh`/px) so the button's pixels match
 * instead of ballooning when the button is large. All crisp detail (rounded
 * corners, outline thickness, bevel lip) is `pixelScale * n`; only the solid
 * face stretches to fill any extra height/width via 9-slice. The outline's
 * inner highlight is held in a fixed `BEVEL_H`-px bottom slice, so it stays a
 * single crisp row pinned to the face/bevel seam at any size. (`scale` is a px
 * shorthand: pixelScale = `${scale}px`.)
 */

const SRC = {
  outline: assetUrl(outlinePng),
  // Full rounded-rect silhouette (light face + dark bevel unioned), used as a
  // single 9-slice mask over a two-stop gradient — one painted fill, so no
  // sub-pixel seam between face and bevel.
  fill: assetUrl(fillPng),
};

// Native-px geometry of the source art.
const UNIT_H  = 16; // full button height (10 face + 6 bevel)
const BEVEL_H =  6; // dark-fill band height
const CORNER  =  3; // 9-slice inset — the rounded-corner staircase is 3 px deep

const DEFAULT_SCALE = 4;
const DEFAULT_LIGHT = "#ffd21e"; // bright, saturated gold
// shadowColor defaults to a darkened `color`.

/** Multiply a #rgb / #rrggbb hex toward black by fraction `f` (0–1). */
function darken(hex: string, f: number): string {
  const m = hex.replace("#", "");
  const n = m.length === 3 ? m.split("").map((c) => c + c).join("") : m;
  const ch = (i: number) => Math.round(parseInt(n.slice(i, i + 2), 16) * (1 - f));
  return `#${[ch(0), ch(2), ch(4)].map((v) => v.toString(16).padStart(2, "0")).join("")}`;
}

/**
 * Build a 9-slice mask-border style (standard + -webkit-) for a white fill PNG
 * with a uniform `slice` inset (native px); `fill` keeps the center so the
 * solid face shows through. `u(n)` renders a native-px count at the current
 * pixel scale. Cast through a string record because the vendor longhands aren't
 * in React's CSSProperties.
 */
function maskBorder(src: string, slice: number, u: (n: number) => string): CSSProperties {
  const source = `url("${src}")`;
  const width = u(slice);
  const v: Record<string, string> = {
    WebkitMaskBoxImageSource: source,
    WebkitMaskBoxImageSlice:  `${slice} fill`,
    WebkitMaskBoxImageWidth:  width,
    WebkitMaskBoxImageRepeat: "stretch",
    maskBorderSource: source,
    maskBorderSlice:  `${slice} fill`,
    maskBorderWidth:  width,
    maskBorderRepeat: "stretch",
  };
  return v as CSSProperties;
}

export interface NineSliceButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  /** Bright, saturated face color (tints the Light Fill). */
  color?: string;
  /** Darker bevel / shadow color (tints the Dark Fill). Defaults to a darkened `color`. */
  shadowColor?: string;
  /** Label color. Defaults to a near-black for contrast on the bright face. */
  textColor?: string;
  /** Rendered size of one source pixel, as any CSS length (e.g. "0.4vh", "4px"). Overrides `scale`. */
  pixelScale?: string;
  /** Px shorthand for pixelScale (pixelScale = `${scale}px`). */
  scale?: number;
  /** Total button height. Defaults to the native 12-px height; larger values stretch the face. */
  height?: string;
  /** Rendered size of one label font-pixel (CSS length). Defaults to half a structural pixel. */
  labelPixel?: string;
}

export const NineSliceButton = forwardRef<HTMLButtonElement, NineSliceButtonProps>(function NineSliceButton(
  { color = DEFAULT_LIGHT, shadowColor, textColor = "#1a1410", pixelScale, scale = DEFAULT_SCALE, height, labelPixel, className, style, children, ...rest },
  ref,
) {
  const ps = pixelScale ?? `${scale}px`;
  // native-px count → rendered length at the current pixel scale.
  const u = (n: number) => `calc(${ps} * ${n})`;
  const h = height ?? u(UNIT_H);
  const bevel = shadowColor ?? darken(color, 0.32);
  // The label rides the retro 8×8 bitmap font (basicpixel) so it reads as
  // pixel-art arcade type rather than a smooth UI font. Sized in font-pixels
  // that scale with the button's unit; uppercased, with "…" → "..." since the
  // atlas has no ellipsis glyph.
  const labelPx = labelPixel ?? `calc(${ps} * 0.5)`;
  const label =
    typeof children === "string" || typeof children === "number" ? (
      <BitmapText unit={labelPx} tracking={`calc(${labelPx} * -0.5)`}>
        {String(children).replace(/…/g, "...").toUpperCase()}
      </BitmapText>
    ) : (
      children
    );

  const layerBase: CSSProperties = {
    position:       "absolute",
    left:           0,
    right:          0,
    imageRendering: "pixelated",
    pointerEvents:  "none",
  };

  return (
    <button
      ref={ref}
      className={`nine-btn font-mono${className ? ` ${className}` : ""}`}
      style={{
        position:       "relative",
        display:        "inline-flex",
        alignItems:     "center",
        justifyContent: "center",
        height:         h,
        minWidth:       u(16),
        // Content rides the light face, so reserve the fixed bevel lip as
        // bottom padding and give a little breathing room each side.
        padding:        `0 ${u(4)} ${u(BEVEL_H)}`,
        border:         "none",
        background:     "none",
        color:          textColor,
        fontSize:       u(3.5),
        fontWeight:     700,
        letterSpacing:  "0.12em",
        textTransform:  "uppercase",
        lineHeight:     1,
        whiteSpace:     "nowrap",
        cursor:         "pointer",
        ...style,
      }}
      {...rest}
    >
      {/* Tinted fill — ONE silhouette-masked box with a two-stop gradient: the
          face color down to the bevel line, then the bevel color for the fixed
          lip. A single painted element means there's no sub-pixel seam between
          face and bevel (two abutting masked bands used to leak a hairline of
          the dark background on fractional scaling). */}
      <span
        aria-hidden
        style={{
          ...layerBase,
          top:        0,
          bottom:     0,
          zIndex:     0,
          background: `linear-gradient(to bottom, ${color} 0, ${color} calc(100% - ${u(BEVEL_H)}), ${bevel} calc(100% - ${u(BEVEL_H)}), ${bevel} 100%)`,
          ...maskBorder(SRC.fill, CORNER, u),
        }}
      />
      {/* Black outline + white highlight — drawn over both fills. Top corners
          and the whole bevel band (incl. the highlight row) keep a fixed pixel
          size; only the plain side-rails stretch. */}
      <span
        aria-hidden
        style={{
          ...layerBase,
          top:               0,
          bottom:            0,
          zIndex:            2,
          borderStyle:       "solid",
          borderWidth:       `${u(CORNER)} ${u(CORNER)} ${u(BEVEL_H)} ${u(CORNER)}`,
          borderColor:       "transparent",
          borderImageSource: `url("${SRC.outline}")`,
          borderImageSlice:  `${CORNER} ${CORNER} ${BEVEL_H} ${CORNER} fill`,
          borderImageWidth:  `${u(CORNER)} ${u(CORNER)} ${u(BEVEL_H)} ${u(CORNER)}`,
          borderImageRepeat: "stretch",
        }}
      />
      <span
        className="nine-btn__content"
        // Nudged down one button-pixel: the pixel caps otherwise sit optically
        // high on the face. `top` (not transform) so the :active press, which
        // animates transform on this span, stays independent.
        style={{ position: "relative", top: u(1), zIndex: 3, display: "inline-flex", alignItems: "center", gap: u(1.5) }}
      >
        {label}
      </span>
    </button>
  );
});
